### ISSUE TITLE
Show users via text onSubmit whether their answer is correct or not

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#43]
Currently, we communicate to the user that their answer was correct/incorrect only by changing the color of the answers.

![screenshot from 2018-05-29 01-13-45](https://user-images.githubusercontent.com/29493001/40646424-f6821952-62dd-11e8-9b0f-53b8631d043e.png)

This is helpful; however, for a11y reasons, it would be good to show text saying "Correct!" or "Incorrect"

**Comment by jarrodyellets** [comment]
I can tackle this issue

**Comment by energydev** [comment]
@jarrodyellets @austintackaberry it looks like this issue may have already been resolved. When working on the new format for questions I saw that this issue appeared to already have been resolved. If this issue is still being worked, the new questions format would impact these changes. When working on Question.js, I made sure the existing code used the new format for questions.

**Comment by austintackaberry** [comment]
The new questions schema will affect this, but yes for all intents and purposes, this issue should be closed.
