### ISSUE TITLE
The user should be able to see their score on every page

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#59]
Now that we are using the Context API to manage user state in App.js state, we should be able to show the user their score.

I was thinking this might be a good use case for a sidebar. As a first step, maybe it should be simple. For example, if there are 6 total questions across all books and all chapters, the user has answered 3 questions and got 1 answer correct, the sidebar could say:

"1 / 3 questions answered correctly"

Eventually, it would make sense to show more information such as breaking it down by book / chapter, providing links to the questions, etc.

**Comment by radotreyes** [comment]
I'd like to try to implement this. Been going at it and I've got a plain sidebar working which displays a numeric score (progress on my fork [here](https://github.com/radotreyes/ydkjs-exercises/tree/rar/sidebar)). I was thinking we should move some of the landing page elements to this sidebar to make room for a more informative home page.

Since it looks like we're moving away from Material UI I'm not sure how to proceed with giving this sidebar styling or behavior. May have to pause and try to settle on a unifying style for the app as a whole?

**Comment by nikrb** [comment]
sounds great!
Just thinking out loud regarding the sidebar "eventually" - are we thinking of having a tree, providing a quick link to all chapters/questions?
Is it too soon to consider how the sidebar will work for mobile?

**Comment by radotreyes** [comment]
Yes, that's what I was thinking. A sidebar is the best place for a navigation tree IMO. I will try to migrate the navigation structure from `Home` to `Sidebar`. We may want to start laying out the wireframe for a true home page/landing page?

On mobile: I think as long as we haven't settled on an overall style for the app yet, it will be too soon to know how to best implement mobile behavior, or just behavior in general, however an [App Bar](https://material-ui.com/demos/app-bar/) with popover menus might be a good place to start brainstorming.

**Comment by austintackaberry** [comment]
Yeah, maybe developing for "desktop with mobile in the back of your mind" might be the way to go for now
